apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- scc-non-root.yaml
- worker-service-account.yaml

secretGenerator:
- name: azure-service-principal
  files:
  - kubernetes.service-principal.json

generatorOptions:
  disableNameSuffixHash: true
