apiVersion: v1
kind: Pod
metadata:
  name: pvc-test-pod
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: example
  containers:
    - name: container
      image: registry.access.redhat.com/ubi9/httpd-24
      ports:
        - containerPort: 8080
          name: "http"
      volumeMounts:
        - mountPath: "/data"
          name: data
